function tests = testRelaxedHamiltonianCache
%TESTRELAXEDHAMILTONIANCACHE Regression tests for cached H(q) assembly.
tests = functiontests(localfunctions);
end

function cachedMatchesDirect(testCase)
a = 1.42*sqrt(3);
stack = getStack(a,[-1.4,0,2.8]);
DoF = getDoF(stack,0.25,3,'clean');
tA = [0,0.3302,0.23206,0.04969,-0.02499, ...
      0.00285,0.00204,-0.00014,-0.00029].';
tB = [-2.99251,-0.28983,0.02791,-0.00877,-0.01870, ...
      0.00621,-0.00256,-0.00018,-0.00033,-0.00264].';
shells = getInterpolatedIntralayerHoppingValues(stack,tA,tB,[]);
fields = makeToyTrilayerRelaxation(stack,0.005*a);
q = stack.K(:,2);

options.verbose = false;
options.intralayer = struct( ...
    'configurationGridSize',3,'useGPU',false,'verbose',false);
options.interlayer = struct( ...
    'realSpaceRadialOrder',8, ...
    'realSpaceAngularOrder',12, ...
    'realSpaceCutoff',5*a, ...
    'configurationGridSize',3, ...
    'minimumConfigurationGridSize',3, ...
    'spectatorModeCutoff',1, ...
    'modeBatchSize',4, ...
    'pairBatchSize',16, ...
    'useGPU',false, ...
    'verbose',false);

direct = buildRelaxedHamiltonian( ...
    stack,DoF,q,shells,fields,options);
cache = prepareRelaxedHamiltonian( ...
    stack,DoF,shells,fields,[q,q+[1e-3;0]],options);
cached = evaluateRelaxedHamiltonian(cache,q);
relativeError = norm(direct-cached,'fro')/max(norm(direct,'fro'),eps);
verifyLessThan(testCase,relativeError,5e-12);
verifyLessThan(testCase, ...
    norm(cached-cached','fro')/max(norm(cached,'fro'),eps),1e-12);
end
