function tests = testModuleBoundaries
%TESTMODULEBOUNDARIES Public APIs are package-qualified and non-overlapping.
tests = functiontests(localfunctions);
end

function publicEntryPointsExist(testCase)
names = [ ...
    "relaxed_dos.computeMomentumLocalDOS", ...
    "relaxed_dos.computeTotalMomentumDOS", ...
    "relaxed_idos.computeMomentumLocalIDOS", ...
    "relaxed_idos.computeTotalIDOS", ...
    "driven_rttg.computeDrivenSpectralObservables", ...
    "rttg_common.blockLanczosHermitian"];
for index = 1:numel(names)
    verifyNotEmpty(testCase,which(names(index)), ...
        sprintf('Missing module entry point %s.',names(index)));
end
end

function obsoleteMixedEntryPointsAreAbsent(testCase)
names = [ ...
    "computeGreenIDOS", ...
    "computeRelaxedGreenIDOS", ...
    "computeRelaxedMomentumIDOSLinecut", ...
    "computeDrivenSpectralObservables"];
for index = 1:numel(names)
    verifyEmpty(testCase,which(names(index)), ...
        sprintf('Obsolete flat entry point %s remains visible.',names(index)));
end
end
