function tests = testIDOSFractalDimension
%TESTIDOSFRACTALDIMENSION Known-measure tests for IDoS scale regression.
tests = functiontests(localfunctions);
end

function uniformMeasureHasDimensionOne(testCase)
E = linspace(0,1,16385);
IDOS = E;
scales = 2.^(-(2:7));
options = struct( ...
    'evaluationEnergies',0.5, ...
    'qOrders',[0,1,2], ...
    'window',[0,1], ...
    'minimumScaleToSmoothingRatio',0);
dimension = relaxed_idos.estimateFractalDimensionsFromIDOS( ...
    E,IDOS,scales,options);

verifyEqual(testCase,dimension.local.dimension,1,'AbsTol',2e-12);
verifyEqual(testCase,dimension.generalized.dimension,ones(1,3), ...
    'AbsTol',2e-12);
verifyGreaterThan(testCase,dimension.local.fitR2,1-1e-12);
verifyGreaterThan(testCase,dimension.generalized.fitR2, ...
    (1-1e-12)*ones(1,3));
end

function atomHasDimensionZero(testCase)
E = linspace(-1,1,20001);
IDOS = double(E >= 0);
scales = 2.^(-(2:7));
options = struct( ...
    'evaluationEnergies',0, ...
    'qOrders',[0,1,2], ...
    'window',[-0.5,0.5], ...
    'minimumScaleToSmoothingRatio',0);
dimension = relaxed_idos.estimateFractalDimensionsFromIDOS( ...
    E,IDOS,scales,options);

verifyEqual(testCase,dimension.local.dimension,0,'AbsTol',2e-12);
verifyEqual(testCase,dimension.generalized.dimension,zeros(1,3), ...
    'AbsTol',2e-12);
end
