clearvars
close all

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(projectRoot));

a = 1.42*sqrt(3);
stack = getStack(a,[-1.4,0,2.8]);
tA = [0,0.3302,0.23206,0.04969,-0.02499, ...
      0.00285,0.00204,-0.00014,-0.00029].';
tB = [-2.99251,-0.28983,0.02791,-0.00877,-0.01870, ...
      0.00621,-0.00256,-0.00018,-0.00033,-0.00264].';
shells = getInterpolatedIntralayerHoppingValues(stack,tA,tB,[]);
% This low-harmonic field only tests the plotting/assembly pipeline. It is
% not the mechanically minimized 0.3-degree field used in Massatt et al.,
% and therefore will not reproduce their long snowflake Fourier tails.
relaxationFields = makeToyTrilayerRelaxation(stack,0.01*a);

% Discrete relaxed real-space bonds for layer 1 at a chosen configuration.
intralayerPlotOptions = struct( ...
    'configurationFractionK',[0;0], ...
    'configurationFractionL',[0;0], ...
    'shellReferenceLayer',2, ...
    'markerSize',60);
plotRelaxedIntralayerHopping( ...
    stack,shells,relaxationFields,1,intralayerPlotOptions);

% Real-space and directly integrated Fourier-space interlayer hopping.
interlayerPlotOptions.realSpace = struct( ...
    'extent',4*a, ...
    'gridSize',121, ...
    'spectatorFraction',[0;0]);
interlayerPlotOptions.fourier = struct( ...
    'realSpaceRadialOrder',80, ...
    'realSpaceAngularOrder',128, ...
    'realSpaceCutoff',15*a, ...
    'configurationGridSize',9, ...
    'batchSize',128, ...
    'useGPU',false, ...
    'transformType','spectatorMode', ...
    'includeBlochNormalization',false);
interlayerPlotOptions.qExtent = 2*pi;
interlayerPlotOptions.qGridSize = 61;
interlayerPlotOptions.spectatorMode = [0;0];
interlayerPlotOptions.fourierComponent = 'magnitude';

[figures,interlayerData] = plotRelaxedInterlayerHopping( ...
    stack,relaxationFields,[1,2],interlayerPlotOptions); %#ok<NASGU,ASGLU>

% For a Figure-4-style comparison, use the mechanically minimized fields
% and transform the same fixed-b3 slice shown in real space:
%
% comparisonOptions.spectatorFraction = [0;0];
% comparisonOptions.qGridSize = 161;
% comparisonOptions.fourier = struct( ...
%     'transformType','spectatorSlice', ...
%     'includeBlochNormalization',true, ...
%     'realSpaceCutoff',8);
% plotInterlayerMassattComparison( ...
%     stack,relaxationFields,[1,2],comparisonOptions);
