clearvars
close all

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(projectRoot));

a = 1.42*sqrt(3);
stack = getStack(a,[-1.4,0,2.8]);
DoF = getDoF(stack,0.35,15,'clean');
q = stack.K(:,2);

tA = [0,0.3302,0.23206,0.04969,-0.02499, ...
      0.00285,0.00204,-0.00014,-0.00029].';
tB = [-2.99251,-0.28983,0.02791,-0.00877,-0.01870, ...
      0.00621,-0.00256,-0.00018,-0.00033,-0.00264].';
shells = getInterpolatedIntralayerHoppingValues(stack,tA,tB,[]);

% Replace these toy fields with the mechanically relaxed fields.
relaxationFields = makeToyTrilayerRelaxation(stack,0.01*a);

useGPU = false;
try
    useGPU = gpuDeviceCount('available') > 0;
catch
end

options.intralayer = struct( ...
    'configurationGridSize',5, ...
    'couplingInnerRadius',6.00, ...
    'couplingOuterRadius',6.25, ...
    'shellReferenceLayer',2, ...
    'useGPU',useGPU, ...
    'verbose',true);

% Use spectatorModeCutoff=inf for the exact finite-L basis. For large L,
% converge a finite value to reduce the number of relaxed scattering modes.
options.interlayer = struct( ...
    'realSpaceRadialOrder',80, ...
    'realSpaceAngularOrder',128, ...
    'realSpaceCutoff',8*a, ...
    'configurationGridSize',[], ...
    'minimumConfigurationGridSize',9, ...
    'spectatorModeCutoff',4, ...
    'momentumInnerRadius',6.00, ...
    'momentumOuterRadius',6.25, ...
    'modeBatchSize',16, ...
    'pairBatchSize',128, ...
    'useGPU',useGPU, ...
    'verbose',true);

[H,parts,info] = buildRelaxedHamiltonian( ...
    stack,DoF,q,shells,relaxationFields,options);

fprintf('\nDimension: %d\n',info.dimension);
fprintf('Full nnz: %d\n',info.numNonzeros);
fprintf('Intralayer nnz: %d\n',nnz(parts.intralayer));
fprintf('Interlayer nnz: %d\n',nnz(parts.interlayer));
fprintf('Relative Hermiticity error: %.3e\n', ...
    info.relativeHermiticityError);

% Convergence checks for production calculations:
%   1. Increase DoF truncations W and L.
%   2. Increase intralayer.configurationGridSize.
%   3. Increase interlayer.spectatorModeCutoff.
%   4. Increase interlayer.configurationGridSize and quadrature orders.
