function tests = testDrivenSpectralObservables
%TESTDRIVENSPECTRALOBSERVABLES Exact central-sector resolvent tests.
tests = functiontests(localfunctions);
end

function centralSpectralMeasureMatchesDirectResolvent(testCase)
baseDimension = 6;
orbitalEnergy = [-1.0,-0.65,-0.2,0.25,0.6,1.05].';
Hfun = @(q) diag(orbitalEnergy+0.08*q(1)-0.03*q(2));
optical = driven_rttg.makeOpticalDriveSource( ...
    0.08,[0.03;0.01],sqrt(2),0.2,1, ...
    struct('type','gaussianTrain','period',20,'fwhm',2,'center',0));
acoustic = driven_rttg.makeAcousticDriveSource( ...
    0.04,[-0.01;0.02],sqrt(3),-0.1,1);
prepareOptions = struct( ...
    'hbar',0.5, ...
    'maximumOpticalDutyCycle',0.1, ...
    'relationSearchOrder',2, ...
    'maximumExtendedDimension',100, ...
    'verbose',false);
cache = driven_rttg.prepareDrivenSpaceTimeHamiltonian( ...
    Hfun,[0.2;-0.1],baseDimension,optical,acoustic,prepareOptions);
cache.defaultSpatialSelector = speye(baseDimension);

E = linspace(-2,2,31);
eta = 0.09;
observableOptions.lanczos = struct( ...
    'maximumBlockSteps',9, ...
    'reorthogonalizationPasses',2, ...
    'breakdownTolerance',1e-13, ...
    'verbose',false);
observableOptions.computeOpticalAcousticContrast = true;
observableOptions.returnMatrixSpectralFunction = true;
observableOptions.verbose = false;
observable = driven_rttg.computeDrivenSpectralObservables( ...
    cache,E,eta,0,observableOptions);

[K,~,~] = driven_rttg.evaluateDrivenSpaceTimeHamiltonian(cache,0);
V = driven_rttg.getDrivenCentralSelector(cache,speye(baseDimension));
[eigenvector,eigenvalue] = eig(full(K),'vector');
exactWeight = abs(V'*eigenvector).^2;
expectedIntegrated = exactWeight*( ...
    0.5+atan((E-eigenvalue)/eta)/pi);
computedIntegrated = squeeze( ...
    observable.combined.orbitalIntegratedMeasure(1,1,:,:));
verifyEqual(testCase,computedIntegrated,expectedIntegrated.', ...
    'RelTol',2e-10,'AbsTol',2e-11);
for energyIndex = [1,8,16,24,31]
    z = E(energyIndex)+1i*eta;
    exactGreen = V'*((K-z*speye(size(K,1)))\V);
    expectedDensity = (exactGreen-exactGreen')/(2i*pi);
    computedDiagonal = squeeze( ...
        observable.combined.orbitalSpectralFunction( ...
        1,1,energyIndex,:));
    computedMatrix = squeeze( ...
        observable.combined.matrixSpectralFunction( ...
        1,1,energyIndex,:,:));
    verifyEqual(testCase,computedDiagonal,real(diag(expectedDensity)), ...
        'RelTol',2e-10,'AbsTol',2e-11);
    verifyEqual(testCase,computedMatrix,expectedDensity, ...
        'RelTol',2e-10,'AbsTol',2e-11);
end

expectedTotal = mean( ...
    observable.combined.orbitalSpectralFunction,4);
verifyEqual(testCase,observable.combined.totalSpectralFunction, ...
    expectedTotal,'AbsTol',1e-14);
for layer = 1:3
    columns = 2*layer+(-1:0);
    expectedLayer = mean( ...
        observable.combined.orbitalSpectralFunction(:,:,:,columns),4);
    verifyEqual(testCase, ...
        observable.combined.layerSpectralFunction(:,:,:,layer), ...
        expectedLayer,'AbsTol',1e-14);
end

increment = diff( ...
    observable.combined.orbitalIntegratedMeasure,1,3);
verifyGreaterThanOrEqual(testCase,increment,-1e-13*ones(size(increment)));
verifyGreaterThanOrEqual(testCase, ...
    observable.combined.boundaryWeightByPole{1}, ...
    -1e-14*ones(size(observable.combined.boundaryWeightByPole{1})));
verifyLessThanOrEqual(testCase, ...
    observable.combined.boundaryWeightByPole{1}, ...
    1+1e-12*ones(size(observable.combined.boundaryWeightByPole{1})));
end

function opticalAcousticContrastUsesInclusionExclusion(testCase)
baseDimension = 2;
H = diag([-0.4,0.7]);
optical = driven_rttg.makeOpticalDriveSource( ...
    0.06,[0;0],sqrt(2),0,1, ...
    struct('type','gaussianTrain','period',20,'fwhm',2,'center',0));
acoustic = driven_rttg.makeAcousticDriveSource( ...
    0.03,[0;0],sqrt(3),0,1);
options = struct( ...
    'hbar',1, ...
    'maximumOpticalDutyCycle',0.1, ...
    'relationSearchOrder',2, ...
    'maximumExtendedDimension',100, ...
    'verbose',false);
cache = driven_rttg.prepareDrivenSpaceTimeHamiltonian( ...
    H,[0;0],baseDimension,optical,acoustic,options);

observableOptions.spatialSelector = speye(baseDimension);
observableOptions.computeOpticalAcousticContrast = true;
observableOptions.lanczos = struct( ...
    'maximumBlockSteps',9,'verbose',false);
observableOptions.verbose = false;
observable = driven_rttg.computeDrivenSpectralObservables( ...
    cache,linspace(-2,2,11),0.1,0,observableOptions);

expected = observable.combined.orbitalSpectralFunction ...
    -observable.opticalOnly.orbitalSpectralFunction ...
    -observable.acousticOnly.orbitalSpectralFunction ...
    +observable.undriven.orbitalSpectralFunction;
verifyEqual(testCase,observable.contrast.orbitalSpectralFunction, ...
    expected,'AbsTol',1e-14);
expectedIntegrated = observable.combined.orbitalIntegratedMeasure ...
    -observable.opticalOnly.orbitalIntegratedMeasure ...
    -observable.acousticOnly.orbitalIntegratedMeasure ...
    +observable.undriven.orbitalIntegratedMeasure;
verifyEqual(testCase,observable.contrast.orbitalIntegratedMeasure, ...
    expectedIntegrated,'AbsTol',1e-14);
end
