function [driveCache,bridge] = prepareRelaxedDrivenSpaceTimeHamiltonian( ...
    stack,DoF,shellsReference,relaxationFields,q, ...
    opticalSources,acousticSources,options)
%PREPARERELAXEDDRIVENSPACETIMEHAMILTONIAN Connect relaxed H(q) to drives.
if nargin < 8
    options = struct;
end
defaults = struct( ...
    'hamiltonian',struct, ...
    'driving',struct, ...
    'matrixCacheSize',1);
options = mergeOptions(options,defaults);

hbar = 1;
if isfield(options.driving,'hbar') && ~isempty(options.driving.hbar)
    hbar = options.driving.hbar;
end
geometry = driven_rttg.getDriveSidebandGeometry( ...
    q,opticalSources,acousticSources,hbar);
staticCache = prepareRelaxedHamiltonian( ...
    stack,DoF,shellsReference,relaxationFields, ...
    geometry.shiftedQ,options.hamiltonian);
Hfun = rttg_common.makeCachedRelaxedHamiltonianFunction( ...
    staticCache,options.matrixCacheSize);
driveCache = driven_rttg.prepareDrivenSpaceTimeHamiltonian( ...
    Hfun,q,staticCache.dimension,opticalSources,acousticSources, ...
    options.driving);
driveCache.defaultSpatialSelector = getCenterBasis(DoF,1:6);
driveCache.defaultCentralSelector = driven_rttg.getDrivenCentralSelector( ...
    driveCache,driveCache.defaultSpatialSelector);

bridge.staticCache = staticCache;
bridge.H = Hfun;
bridge.qPoints = geometry.shiftedQ;
bridge.baseDimension = staticCache.dimension;
end
