function validation = validateDriveSources( ...
    opticalSources,acousticSources,baseDimension,options)
%VALIDATEDRIVESOURCES Validate source data, pulses, and thermal guardrails.
if nargin < 4
    options = struct;
end
defaults = struct( ...
    'maximumOpticalDutyCycle',0.10, ...
    'requirePulsedOpticalSources',true);
options = mergeOptions(options,defaults);
assert(isscalar(baseDimension) && baseDimension >= 1 && ...
    baseDimension == fix(baseDimension), ...
    'baseDimension must be a positive integer.');
assert(options.maximumOpticalDutyCycle > 0 && ...
    options.maximumOpticalDutyCycle <= 1, ...
    'maximumOpticalDutyCycle must lie in (0,1].');

validation.opticalPulseMetrics = cell(numel(opticalSources),1);
for index = 1:numel(opticalSources)
    validateCommon(opticalSources(index),baseDimension,'optical');
    envelopeType = lower(string(opticalSources(index).envelope.type));
    if options.requirePulsedOpticalSources
        assert(envelopeType ~= "constant", ...
            'Optical source %d must use a pulsed envelope.',index);
    end
    metrics = driven_rttg.getOpticalPulseMetrics( ...
        opticalSources(index));
    if isfinite(metrics.equivalentIntensityDutyCycle)
        assert(metrics.equivalentIntensityDutyCycle <= ...
            options.maximumOpticalDutyCycle, ...
            ['Optical source %d has equivalent intensity duty cycle ' ...
             '%.4g, exceeding the configured limit %.4g.'], ...
            index,metrics.equivalentIntensityDutyCycle, ...
            options.maximumOpticalDutyCycle);
    end
    if isfinite(metrics.estimatedAverageIntensity) && ...
            isfinite(metrics.maximumAverageIntensity)
        assert(metrics.estimatedAverageIntensity <= ...
            metrics.maximumAverageIntensity, ...
            ['Optical source %d exceeds its configured average-intensity ' ...
             'limit.'],index);
    end
    validation.opticalPulseMetrics{index} = metrics;
end

for index = 1:numel(acousticSources)
    validateCommon(acousticSources(index),baseDimension,'acoustic');
end

validation.warning = ['A pulse-duty check is not a thermal model and ' ...
    'cannot guarantee that a device will avoid damage. Safe laboratory ' ...
    'limits require measured absorption, heat removal, spot geometry, ' ...
    'substrate properties, and device-specific damage thresholds.'];
end

function validateCommon(source,baseDimension,expectedKind)
required = {'kind','amplitude','waveVector','frequency','phase', ...
    'cutoff','envelope','couplingOperator'};
for field = required
    assert(isfield(source,field{1}), ...
        'A %s source is missing field "%s".',expectedKind,field{1});
end
assert(strcmpi(source.kind,expectedKind), ...
    'Expected a %s source.',expectedKind);
assert(isscalar(source.amplitude) && isfinite(source.amplitude) && ...
    source.amplitude >= 0,'Source amplitude must be nonnegative.');
assert(isequal(size(source.waveVector),[2,1]) && ...
    all(isfinite(source.waveVector)), ...
    'Source waveVector must be a finite 2-by-1 vector.');
assert(isscalar(source.frequency) && isfinite(source.frequency) && ...
    source.frequency > 0,'Source frequency must be positive.');
assert(isscalar(source.phase) && isfinite(source.phase), ...
    'Source phase must be finite.');
assert(isscalar(source.cutoff) && source.cutoff >= 0 && ...
    source.cutoff == fix(source.cutoff), ...
    'Source cutoff must be a nonnegative integer.');
assert(isstruct(source.envelope) && isfield(source.envelope,'type'), ...
    'Source envelope must be a structure containing type.');
evaluateDriveEnvelope(source,0);
if ~isempty(source.couplingOperator)
    assert(isequal(size(source.couplingOperator), ...
        [baseDimension,baseDimension]), ...
        'A couplingOperator must be baseDimension-by-baseDimension.');
end
end
