clearvars
close all

projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(projectRoot));

% Momentum-local integrated spectral measure N_eta(q,E) along the paper's
% K1-K2-Gamma12-Gamma23-K2-K3 path.  Increase W, L, quadrature orders,
% Lanczos depth, and pointsPerSegment for production calculations.
a = 1.42*sqrt(3);
stack = getStack(a,[-0.3,0,0.3]);
W = 0.04;
L = 3;
DoF = getDoF(stack,W,L,'clean');

tA = [0,0.3302,0.23206,0.04969,-0.02499, ...
      0.00285,0.00204,-0.00014,-0.00029].';
tB = [-2.99251,-0.28983,0.02791,-0.00877,-0.01870, ...
      0.00621,-0.00256,-0.00018,-0.00033,-0.00264].';
shells = getInterpolatedIntralayerHoppingValues(stack,tA,tB,[]);
relaxationFields = makeToyTrilayerRelaxation(stack,0.01*a);

pointsPerSegment = 8;
linecut = rttg_common.getLinecut(stack.K,pointsPerSegment);
E = linspace(-1,1,1001);
eta = 0.02; % eV: Poisson/Lorentzian resolvent broadening

hamiltonianOptions.verbose = false;
hamiltonianOptions.intralayer = struct( ...
    'configurationGridSize',3,'useGPU',false,'verbose',false);
hamiltonianOptions.interlayer = struct( ...
    'realSpaceRadialOrder',12, ...
    'realSpaceAngularOrder',18, ...
    'realSpaceCutoff',6*a, ...
    'configurationGridSize',3, ...
    'minimumConfigurationGridSize',3, ...
    'spectatorModeCutoff',1, ...
    'modeBatchSize',4, ...
    'pairBatchSize',16, ...
    'useGPU',false, ...
    'verbose',false);

greenOptions.lanczos = struct( ...
    'maximumBlockSteps',80, ...
    'reorthogonalizationPasses',2, ...
    'breakdownTolerance',1e-12, ...
    'verbose',false);
greenOptions.energyChunkSize = 512;
greenOptions.storeLanczos = false;

options.hamiltonian = hamiltonianOptions;
options.green = greenOptions;
options.matrixCacheSize = min(size(linecut.q,2),8);
options.verbose = true;

[result,bridge] = ...
    relaxed_idos.computeRelaxedMomentumLocalIDOSLinecut( ...
    stack,DoF,shells,relaxationFields,linecut,E,eta,options); %#ok<ASGLU>

plotOptions.title = ...
    'Relaxed momentum-local integrated measure';
plotOptions.view = [45,32];
relaxed_idos.plotMomentumLocalIDOSLinecut( ...
    linecut,E,result.momentumLocalIDOS,eta,plotOptions);

% This example intentionally plots only the cumulative IDoS.  The paper's
% Jackson-KPM momentum LDoS is computed by the separate relaxed_dos module.
